### ISSUE TITLE
Desktop Environment support

### ISSUE THREAD

**Issue by heller390** [yuk7/ArchWSL2#2]
I was able to  get xfce4 full de on wsl. But trying the same thing on wsl2 gives error. Tried with VcxSrv and RDP but in vain. Systemd , dbus all seem to be running fine .  Any help is appreciated

https://www.reddit.com/r/bashonubuntuonwindows/comments/fawx1j/xfce_4_linux_desktop_on_wsl_windows_subsystem_for/

**Comment by Potato1682** [comment]
What is the value of $DISPLAY?

**Comment by heller390** [comment]
> What is the value of $DISPLAY?

export DISPLAY=127.0.0.1:0.0 . This worked on wsl 1.

**Comment by Potato1682** [comment]
WSL 1 and WSL 2 have different network structures.
Something related to name resolution, such as an IP address, is virtually assigned to another IP address.
With WSL 2, you can connect over vEthernet.
Execute this command may help.
```sh
export DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}'):0.0
```
P.S. It is recommended to put this command in `.bashrc` or `.zshrc` because the vEthernet address of WSL 2 is always changed.

**Comment by heller390** [comment]
> 
> 
> WSL 1 and WSL 2 have different network structures.
> Something related to name resolution, such as an IP address, is virtually assigned to another IP address.
> With WSL 2, you can connect over vEthernet.
> Execute this command may help.
> 
> ```shell
> export DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}'):0.0
> ```
> 
> P.S. It is recommended to put this command in `.bashrc` or `.zshrc` because the vEthernet address of WSL 2 is always changed.

This and selecting an option in VcxSrv to disable access control did the trick.
